---
site_name: mockafka
site_author: Ali Moradi
site_description: >-
  Documentation for MocKafka python library
# Repository
repo_name: xibalbas/mockafka
repo_url: https://github.com/xibalbas/mockafka-py

# Copyright
copyright: Copyright &copy; 2023 - 2024 Ali Moradi

plugins:
  - search:
      lang: en


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cunla
      repo: fakeredis
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 2
nav:
  - Home: index.md
  - decorators: decorators.md
  - fake admin client: fake-admin-client.md
  - fake consumer: fake-consumer.md
  - fake producer: fake-produce.md
  - kafka store: kafka-store.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  highlightjs: true
  hljs_languages:
    - yaml
    - django
extra:
  generator: false
  analytics:
    provider: google
    property: G-GJBJBKXT19

  annotate:
    json: [ .s2 ]

  version:
    default:
      - stable
      - development
